### ISSUE TITLE
Root level widget not being removed after level transition

### ISSUE THREAD

**Issue by infinstarlight** [goncasmage1/UINavigation#168]
Hey there! 
I'm using a duplicate of the Simple Pack Main Menu widget for my project and I had it set to not remove if root. And when I start a new game (by using OpenLevel) the main menu widget persists over my gameplay level even though it is supposed to be removed. The widget is being added by my player controller from a Game Mode override. 

![image](https://user-images.githubusercontent.com/3934211/205607708-fbcd1323-fb92-42ca-b4b5-ef633c74ed80.png)
_The main menu level_

![image](https://user-images.githubusercontent.com/3934211/205607733-ec5c6396-2d65-4863-b42c-6b41a8675fd2.png)
_The gameplay level with the main menu widget persisting_

My current solution is to the Gameplay GM (the default within project settings) check if the widget exists and then remove it on the HandleStartingNewPlayer event (not sure if its the most appropriate, just seemed like the better option)

![image](https://user-images.githubusercontent.com/3934211/205608593-12172721-027e-48e9-a0cc-5fd704804ae2.png)
_Temp solution events_

I had double checked the overrides, made sure the widget wasn't being created elsewhere and had reenabled the allow remove if root option and the issue remained. Is this consistent behavior or is there a bug here?

I appreciate the help in advance!

**Comment by goncasmage1** [comment]
Hello,

The AllowRemoveIfRoot shouldn't be considered when removing a menu between
levels. If it's not being removed, it's most likely due to a missing setup
step somewhere, because the UINav Simple Pack itself doesn't cause this
when switching levels using the OpenLevel function. Maybe you can check how
the GameMode is set and overridden across its maps.

Regards,
Gonçalo.
