### ISSUE TITLE
Event OnSelect not firing when not using the mouse to select.

### ISSUE THREAD

**Issue by shukenmg** [goncasmage1/UINavigation#62]

**Comment by goncasmage1** [comment]
Hi @shukenmg 
This is a well known bug that will take some time to fix.
Your pull request won't properly fix the issue, however, you can tick the UseClickEventForSelect boolean to true, in the widget's Class Defaults, in order to fix the issue

**Comment by shukenmg** [comment]
Thank you for your help.

I was just wondering what would be needed to fix the issue properly?

**Comment by goncasmage1** [comment]
Well the reason why the event is not being called properly is because that line of code that broadcasts the OnPressed delegate, near the line of code you added, is in reality broadcasting the OnClicked event (god knows why).
If that event would be broadcast properly, that would fix the issue and allow me to continue working on other things inside the plugin.

If you could help me investigate this, that would be great 😄

**Comment by shukenmg** [comment]
@goncasmage1 
For some reason when I uncommented the OnPressed Delegate it now works properly.

**Comment by shukenmg** [comment]
@goncasmage1 
Ok, when I uncomment the OnPressed Delegate and then compile it still runs the on clicked event, but if I relaunch the editor it fixes the problem.

**Comment by shukenmg** [comment]
@goncasmage1 
Interesting...

Would it be possible to tell me how to replicate the issue?
Thanks.

**Comment by goncasmage1** [comment]
Well if you have the UseClickEventForSelect boolean set to false and the OnSelect event doesn't work, you've replicated the issue.

**Comment by shukenmg** [comment]
Ok I think understand, so you made a workaround and to enable the workaround I use the UseClickEventForSelect Boolean.

Is there a trade off when using that workaround?

**Comment by goncasmage1** [comment]
The difference is it being triggered when you Click the button instead of when you Press it. If you leave it at false it'll be triggered when you press the button (but also won't work (for now)
